[tool.bumpversion]
current_version = "1.0.2"
commit = true
tag = true
tag_name = "sandbox-v{new_version}"
tag_message = "Bump sandbox version: {current_version} → {new_version}"
message = "Bump sandbox version: {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "VERSION"

[[tool.bumpversion.files]]
filename = "package.json"
search = "\"version\": \"{current_version}\""
replace = "\"version\": \"{new_version}\""
